# Generated by Django 4.2.4 on 2025-05-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_job_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('gpa', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillSets',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('skills', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
