# Generated by Django 4.2.4 on 2025-05-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_customuser_full_name_customuser_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
