# Generated by Django 4.2.4 on 2025-05-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_education_id_alter_education_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.CharField(max_length=100),
        ),
    ]
