# Generated by Django 4.2.4 on 2025-05-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_education_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='education_list',
            field=models.JSONField(null=True),
        ),
    ]
