# Generated by Django 4.2.4 on 2025-05-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_customuser_education_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
